Update merge-sort.md
joaoarthurbm/eda pull request #27
Opened 2020-10-01 20:58 UTC by ViniciusFurtado1

Professor, a condição de continuidade do merge sort não seria 'if(left < right)' , como foi citado anteriormente ?

2020-10-01 23:11 UTC, joaoarthurbm requested changes
Oi, a condição de continuidade é left < right. O que quis dizer ali é que poderia ter feito algo como:

```
if left >= right
    return;
else
    ....
```

Entende? Mas para poupar as 3 linhas iniciais, eu usei a condição de continuação (que não precisa do else) ao invés da condição de parada. 

Mesmo assim, há um erro. Quer modificar para >=, por favor ?

2020-10-02 00:04 UTC, ViniciusFurtado1 commented
Olá professor, boa noite, como a condição de parada é: (left >= right), temos o código:

```
if left >= right
    return;
else
    ....
```

Já quando fazemos com uma condição de continuidade, invertemos a lógica e o código fica:

```
if left < right
   ....

```
Não é isso?

Eu não entendi o porque de no material estar escrito "Certamente eu poderia ter feito if (left **>** right) e economizado algumas linhas de código descartando o else ...". Se a condição de continuidade, que é o que nos faz eliminar o else, 
é if (left **<** right). Eu só acho que esse Maior que deveria ser trocado pelo Menor que. Posso estar confundido algo...

2020-10-02 13:20 UTC, joaoarthurbm commented
Oi, @ViniciusFurtado1 . Você está certo. Foi isso que tentei te explicar no meu comentário anterior. Quer fazer essa mudança e submeter? Eu aguardo.

2020-10-02 16:01 UTC, joaoarthurbm approved these changes
Perfeito. Obrigado!

2020-10-02 16:02 UTC, merged