Adiconando material transcrito de AVL
joaoarthurbm/eda pull request #95
Opened 2022-03-24 15:39 UTC by pserey

Fala, João!

Adicionei a página em markdown do assunto de AVL. O texto é praticamente o mesmo do [material no docs](https://docs.google.com/document/d/15of_HZ-K1xo2X4F3hBxqS9oP04ewSN7bB3eTuDI3Ewk/edit) com a adição de:
- leves correções de erros de digitação
- sugestões de mudança de texto
- atualização do padrão do código para o usado em materiais recentes
- imagens novas

2022-03-25 14:33 UTC, joaoarthurbm requested changes
Muito bom, @pserey ! Eu foquei inicialmente na formatação. Deixei o que e como fazer.

2022-03-25 14:33 UTC, joaoarthurbm commented on content/posts/avl.md
> +> Mudar as palavras (não entendi exatamente o que quer dizer)
Cuidado. Isso não é comentário em markdown. Dá uma olhada aqui sobre como comentar: https://stackoverflow.com/questions/4823468/comments-in-markdown

2022-03-25 14:33 UTC, joaoarthurbm commented on content/posts/avl.md
> +> Escreva os métodos a seguir:
Desafio. Implemente os métodos a seguir:

2022-03-26 17:12 UTC, pserey commented
Pronto! Tudo corrigido! :)

2022-04-12 22:52 UTC, joaoarthurbm approved these changes
Excelente! Obrigado, @pserey

2022-04-12 22:52 UTC, merged